/**
 * Error generated by API when searching for jokes
 */
export default class ResponseError extends Error {
    code: number

    /**
     * constructs the ResponseError class
     * @param code - error code
     * @param message - error message
     */
    constructor(code: number, message: string) {
        super(message)
        this.name = this.constructor.name
        this.code = code
    }
}
